spring.application.name=AgriProject

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Configuration
server.port=${PORT:8080}

# DataSource Configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:uploads/

# JPA & Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Wait for Hibernate to create tables before running data.sql
spring.jpa.defer-datasource-initialization=true

# --- SQL Initialization Configuration ---

# Use this after the first run (prevents re-inserting data on app restarts)
spring.sql.init.mode=never

spring.sql.init.continue-on-error=true

# Allow bigger file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#something random for secret key
jwt.secretKey=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG

twilio.whatsapp.number=${TWILIO_WHATSAPP_NUMBER}
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}


# Excel export configuration

excel.export.batch.size=50
excel.export.batch.timeout=5000

# Logging
logging.level.com.example.AgriProject=DEBUG
logging.level.org.springframework.transaction=DEBUG


spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=35
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=AgriPool

app.backend.url=${BACKEND_URL}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect