spring.application.name=AgriProject

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Configuration
server.port=

# DataSource Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.static-path-pattern=
spring.web.resources.static-locations=


# JPA & Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Tell Hibernate to use the 'agribazar' schema for tables (optional for MySQL)
# spring.jpa.properties.hibernate.default_schema=agribazar

# Wait for Hibernate to create tables before running data.sql
spring.jpa.defer-datasource-initialization=true

# --- SQL Initialization Configuration ---

# Use this after the first run (prevents re-inserting data on app restarts)
spring.sql.init.mode=never

# Use this ONLY for the very first run when initializing schema/data:
# spring.sql.init.mode=always

spring.sql.init.continue-on-error=true

# Allow bigger file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#something random for secret key
jwt.secretKey=
logging.level.org.springframework.security=DEBUG

razorpay.api.key=
razorpay.api.secret=


twilio.whatsapp.number=
twilio.account.sid=
twilio.auth.token=


# Excel export configuration
excel.export.path=
excel.export.batch.size=50
excel.export.batch.timeout=5000

# Logging
logging.level.com.example.AgriProject=DEBUG
logging.level.org.springframework.transaction=DEBUG